Simple button(fix #1)
MMorihiro/LearningTDD pull request #10
Opened 2016-10-06 12:07 UTC by MMorihiro

#1

2016-10-07 12:09 UTC, forestone23 commented
ベースブランチは`develop`にすべきだと思うから #3 をマージした後に変更しといて。

2016-10-08 09:52 UTC, MMorihiro commented
その通りだね。変更しといた。

2016-10-08 11:34 UTC, forestone23 requested changes

2016-10-08 11:34 UTC, forestone23 commented on core/src/main/com/github/mmorihiro/core/LifeGame.kt
>          val table = Table()
前のプルリクエストで言い忘れちゃったけど`create`関数が見づらいから適当に空行追加しといて。

2016-10-08 11:34 UTC, forestone23 commented on core/src/main/com/github/mmorihiro/core/LifeGame.kt
> +            button.isPressed
この文法が調べてもよくわからないんだけど、Kotlinでも`return`は省略できるんだっけ?

2016-10-08 11:34 UTC, forestone23 commented on core/src/main/com/github/mmorihiro/core/LifeGame.kt
> +        stage.viewport.update(width, height, true)
libGDXのリサイズの仕組み良く分からないんだけど、引き伸ばされちゃうのは仕様?
![image](https://cloud.githubusercontent.com/assets/22497946/19212850/4abcbb2c-8d96-11e6-93ab-fad3fa2b7056.png)

2016-10-08 11:45 UTC, MMorihiro commented on core/src/main/com/github/mmorihiro/core/LifeGame.kt
> +        stage.viewport.update(width, height, true)
だと思うよ。viewportは画面のサイズに応じて自動で調整して描画してくれるんだと思う。
viewportの目的として、libgdxはandroidもサポートしていて端末の大きさの違いを吸収するためというのがあるから、今回のようにデスクトップ向けだけの場合はサイズを固定してもいいかもね。
というか、サイズの固定の有無は`Desktoplauncher`内でできるから他のプロジェクトに影響を与えることもないし、固定してみるよ。
参考: http://mikio.github.io/article/2014/06/02_libgdx-beginner2.html#sec-4-2

2016-10-08 11:46 UTC, mmorihiro commented on core/src/main/com/github/mmorihiro/core/LifeGame.kt
>          val table = Table()
#11 で整理するよ。

2016-10-08 12:04 UTC, MMorihiro commented on core/src/main/com/github/mmorihiro/core/LifeGame.kt
> +            button.isPressed
sam変換のときの引数は関数オブジェクトを生成する無名関数で、この場合は`EventListener -> Boolean`であり、
ラムダ式や無名関数では`return`は省略できるんだと思う。
参考: 
http://qiita.com/RyotaMurohoshi/items/01b370f34a4bf96f5c39
http://qiita.com/k5n/items/964d765767a65cc3de5b#%E3%83%A9%E3%83%A0%E3%83%80%E5%BC%8F%E3%81%A8%E7%84%A1%E5%90%8D%E9%96%A2%E6%95%B0 のラムダ式と無名関数の項あたり

2016-10-09 11:11 UTC, forestone23 commented on core/src/main/com/github/mmorihiro/core/LifeGame.kt
> +            button.isPressed
なるほど難しい…

本題とは関係ないけど、JavaScriptのアロー関数とかScalaのlambda`引数 -> { 式 }`を使ってきた身からするとKotlinの記法`{ 引数 -> 式 }`は違和感がすごい

2016-10-09 11:13 UTC, forestone23 commented on core/src/main/com/github/mmorihiro/core/LifeGame.kt
> +        stage.viewport.update(width, height, true)
他のPRでサイズ固定にする？

2016-10-09 11:14 UTC, MMorihiro commented on core/src/main/com/github/mmorihiro/core/LifeGame.kt
> +        stage.viewport.update(width, height, true)
0c59c98 でどうだろう?

2016-10-09 11:15 UTC, forestone23 commented on core/src/main/com/github/mmorihiro/core/LifeGame.kt
> +        stage.viewport.update(width, height, true)
あと`resize`関数は残しとくの?

2016-10-09 11:22 UTC, MMorihiro commented on core/src/main/com/github/mmorihiro/core/LifeGame.kt
> +            button.isPressed
難しいよね... 
まあ、モナドとかは全く理解できないから、
KotlinがScalaほど関数型の特徴が使えないのは困らないかな(使いこなせないだけだけど... :cry: )

2016-10-09 11:30 UTC, mmorihiro commented on core/src/main/com/github/mmorihiro/core/LifeGame.kt
> +        stage.viewport.update(width, height, true)
ああ、気付いてなかった。Thank you.

2016-10-09 11:34 UTC, forestone23 approved these changes

2016-10-09 11:40 UTC, merged