Increment generation
MMorihiro/LearningTDD pull request #12
Opened 2016-10-09 00:14 UTC by MMorihiro

#11

2016-10-09 09:46 UTC, mmorihiro commented on core/src/main/com/github/mmorihiro/core/GameState.kt
> +        table.debug = true
`true`にすると線が描画されるようになって配置しやすい。最終的には削除する。

2016-10-09 10:44 UTC, mmorihiro commented on core/src/main/com/github/mmorihiro/core/LifeGame.kt
> +        table.addActor(button)
現在は`button`と`label`の2つだけだけだからいいけれど、増えてきた場合には配置の仕方が面倒になりそうなので、その場合は `WidgetGroup`を使おうと思います。

2016-10-09 10:47 UTC, mmorihiro commented on core/src/main/com/github/mmorihiro/core/GameState.kt
> +    }
通常の処理に何も加えていないカスタムゲッターとセッターです。将来的にはここにカスタムの処理を加えようと思います。

2016-10-09 10:55 UTC, MMorihiro commented on core/src/main/com/github/mmorihiro/core/LifeGame.kt
> +        val generation = Label(state.generation.toString(), skin)
直接文字列を描画するよりも、`Label`を使った方がコンストラクタに文字列を渡すだけでいいので便利。

2016-10-09 11:02 UTC, MMorihiro commented on core/src/main/com/github/mmorihiro/core/LifeGame.kt
> +    private fun stage() = state.stage
呼び出しごとに`state.stage`と書いて冗長になるのを避けるためのメソッド。

2016-10-09 11:06 UTC, MMorihiro commented on desktop/src/com/github/mmorihiro/desktop/DesktopLauncher.java
> +        config.backgroundFPS = 10;
fpsを固定。10は少なすぎかな。
世代の更新周期を100ミリ秒にしようと思っているから、
fpsをそれに合わせると余計な処理をしなくていいからなんだけど。(手抜き)

2016-10-09 11:08 UTC, MMorihiro commented on core/src/main/com/github/mmorihiro/core/LifeGame.kt
> -    override fun create() {
初期化の処理も多くなってきたので`GameState`に移動。

2016-10-09 11:47 UTC, forestone23 commented
コンフリクトの解決お願い。

2016-10-10 10:00 UTC, forestone23 requested changes

2016-10-10 10:00 UTC, forestone23 commented on core/src/main/com/github/mmorihiro/core/GameState.kt
> +    }
getter/setterはインデントしたほうが見やすいんじゃない?

2016-10-10 10:00 UTC, forestone23 commented on core/src/main/com/github/mmorihiro/core/LifeGame.kt
> +   private val state by lazy {
細かいけどこの行インデントずれてるよ

2016-10-10 10:00 UTC, forestone23 commented on core/src/main/com/github/mmorihiro/core/LifeGame.kt
> +    private fun stage() = state.stage
private valとgetter使うのがいい気がするけど、Kotlinではこういうの関数にするの？

2016-10-10 10:00 UTC, forestone23 commented on core/src/main/com/github/mmorihiro/core/GameState.kt
> +    private val skin = Skin(Gdx.files.internal("uiskin.json"))
`skin`がdisposeされてないみたい。

2016-10-11 11:01 UTC, MMorihiro commented on core/src/main/com/github/mmorihiro/core/LifeGame.kt
> +   private val state by lazy {
Intellij IDEAではコミット時にオプションとして`reformat code`を指定できるから、それをonにして常にフォーマットされているようにするよ。

2016-10-11 11:16 UTC, MMorihiro commented on core/src/main/com/github/mmorihiro/core/GameState.kt
> +    private val skin = Skin(Gdx.files.internal("uiskin.json"))
`stage`をdisposeすれば自動的にdisposeされるかと思ってたけど、違うみたい。

2016-10-11 11:17 UTC, MMorihiro commented on core/src/main/com/github/mmorihiro/core/LifeGame.kt
> +    private fun stage() = state.stage
確かにget用のプロパティを使ったがいいね。

2016-10-11 11:50 UTC, forestone23 requested changes

2016-10-11 11:50 UTC, forestone23 commented on core/src/main/com/github/mmorihiro/core/LifeGame.kt
> +    }
これ、`stage`が最初に呼ばれた時に`stage`に`state.stage`が代入されて、それ以降`state.stage`の中身が変わっても`stage`は更新されない気がする…(説明下手でごめん)
一応こうしといたほうが安全だと思う

```kotlin
private val stage: Stage
    get() = state.stage
```

2016-10-11 11:53 UTC, mmorihiro commented on core/src/main/com/github/mmorihiro/core/LifeGame.kt
> +    }
確かにそちらの方が安全だね。
でも今回は`state.stage`は`var`ではなく`val`で再代入不可だからそこまではいいんじゃないかな?

2016-10-11 11:58 UTC, forestone23 commented on core/src/main/com/github/mmorihiro/core/LifeGame.kt
> +    }
確かにそうだったね。
あと今調べて気づいたんだけど、Javaでインスタンスを他の変数に代入するときはCloneされるものだと勘違いしてた。
http://java.keicode.com/lang/clone.php

2016-10-11 11:58 UTC, forestone23 approved these changes
[![LGTM](https://lgtm.in/p/Ig1FwdbOp)](https://lgtm.in/i/Ig1FwdbOp)

2016-10-12 10:47 UTC, merged