fix #6 Reset Button
MMorihiro/LearningTDD pull request #15
Opened 2016-10-10 08:52 UTC by MMorihiro

#6

2016-10-10 08:53 UTC, mmorihiro commented on core/src/main/com/github/mmorihiro/core/GameState.kt
> +internal class GameState {
わざわざ`public`にする必要もないので公開範囲を限定。

2016-10-10 08:54 UTC, mmorihiro commented on core/src/main/com/github/mmorihiro/core/SetUpUILook.kt
> +internal class SetUpUILook(generation: Int) {
`GameState`の処理が多くなってきたので、UIの見た目に関する部分を抽出。

2016-10-10 08:57 UTC, mmorihiro commented on core/src/main/com/github/mmorihiro/core/GameState.kt
> +    fun stage() = setup.stage
stageを`SetUpUILook`に移動したので、stageを`LifeGame`が引き続き取得出来るようにゲッターメソッドを追加。

2016-10-10 09:00 UTC, MMorihiro commented on core/src/main/com/github/mmorihiro/core/GameState.kt
> +        val resetButton = setup.resetButton
いちいち`setup.somebutton`と書くのは面倒なので、一度メソッド内で参照を取得してしまう。

2016-10-10 11:02 UTC, forestone23 requested changes

2016-10-10 11:02 UTC, forestone23 commented on core/src/main/com/github/mmorihiro/core/GameState.kt
> +            stopButton.isPressed
ここ`resetButton.isPressed`だよね

2016-10-11 11:27 UTC, MMorihiro commented on core/src/main/com/github/mmorihiro/core/GameState.kt
> +            stopButton.isPressed
そこね。コピペの際に修正し忘れてた。

2016-10-23 07:46 UTC, ciffelia approved these changes

2016-10-23 07:48 UTC, forestone23 approved these changes

2016-10-23 07:54 UTC, merged