Making new generation
MMorihiro/LearningTDD pull request #35
Opened 2016-11-01 07:53 UTC by mmorihiro

Fix for #33

2016-11-01 08:01 UTC, mmorihiro commented on core/src/main/com/github/mmorihiro/core/ArrayActor.kt
> +    private var array = Array(arraySize) { BooleanArray(arraySize) { false } }
cf839914a06b1a7455e726547204560952647976 was my mistake. I noticed when implementing 8bc327ef971d75d4c9125b5148b09c2beed38748.
This member should be `var` to make new generation.

2016-11-01 08:04 UTC, mmorihiro commented on core/src/main/com/github/mmorihiro/core/ArrayActor.kt
> +    }
As old data is killed by one generation, now I use blinker that is not killed.

2016-11-01 08:11 UTC, mmorihiro commented on core/src/main/com/github/mmorihiro/core/MakeNewGeneration.kt
> +    }
Copying array is very important. Actually, not knowing `Array.copyOf` uses shallow copy, I spent long time.
We have to use deep copy and write the code ourselves.

2016-11-01 08:13 UTC, mmorihiro commented on core/src/test/com.github.mmorihiro.core/TestMakeNewGeneration.kt
> +                array[1][1] shouldBe false
This shows that `array.copyOf` uses shallow copy.

2016-11-01 08:25 UTC, mmorihiro commented on core/src/main/com/github/mmorihiro/core/MakeNewGeneration.kt
> +                        if (pair.first == true && pair.second >= 4)
I use the alternative way that uses `if` statement although this code is in `when` statement.
I don't know how to implement it without using `if`.

2016-11-01 08:29 UTC, mmorihiro commented on core/src/test/com.github.mmorihiro.core/TestMakeNewGeneration.kt
> +                forAll(table) { x, y -> actual[x][y] shouldBe true }
I wonder if these `x` and `y` should be reversed.

2016-11-01 11:24 UTC, forestone23 requested changes

2016-11-01 11:24 UTC, forestone23 commented on core/src/test/com.github.mmorihiro.core/TestMakeNewGeneration.kt
> +            when there are three living cell adjacent to one dead cell""" {
I think this should be:

``` kotlin
"""
|make new generation
|when there are three living cell adjacent to one dead cell
""".trimMargin() {
```

or the test output contains unnecessary tabs.

2016-11-01 11:24 UTC, forestone23 commented on core/src/test/com.github.mmorihiro.core/TestMakeNewGeneration.kt
> +                val table = table(
I'm afraid this causes name collision. It must be `val expectAlive = table(`.

2016-11-01 11:24 UTC, forestone23 commented on core/src/main/com/github/mmorihiro/core/MakeNewGeneration.kt
> +            for (j in array[0].indices) {
I think this should be `array[i]`.

2016-11-01 11:24 UTC, forestone23 commented on core/src/main/com/github/mmorihiro/core/MakeNewGeneration.kt
> +        val copy = copy(array)
I'm afraid this causes name collision.

2016-11-01 11:36 UTC, mmorihiro commented on core/src/test/com.github.mmorihiro.core/TestMakeNewGeneration.kt
> +                val table = table(
Yeah. I also think so. `table` is too simple.

2016-11-01 11:59 UTC, mmorihiro commented on core/src/test/com.github.mmorihiro.core/TestMakeNewGeneration.kt
> +                val table = table(
Could you fix it?

2016-11-01 12:01 UTC, forestone23 commented on core/src/test/com.github.mmorihiro.core/TestMakeNewGeneration.kt
> +                val table = table(
Sure.

2016-11-01 12:09 UTC, mmorihiro commented on core/src/main/com/github/mmorihiro/core/MakeNewGeneration.kt
> +            for (j in array[0].indices) {
Oh, that is a nice idea.
I wondered how to write this and chose a not good way using `array[0]` because I thought this is not a big problem in this case.
Anyway, using `array[i]` is elegant.
Would you rewrite by `array[i]`?

2016-11-02 05:28 UTC, mmorihiro commented on core/src/test/com.github.mmorihiro.core/TestMakeNewGeneration.kt
> +            when there are three living cell adjacent to one dead cell""" {
I almost always agree to use `trimMargin` with multi line string.
Please rewrite it and the code gets better.
Sad to say,
Intellij doesn't have any support for converting ordinary multi line string into the form that uses `trimMargin` in Kotlin even though Intellij has the support for Scala.

2016-11-02 05:34 UTC, mmorihiro commented on core/src/main/com/github/mmorihiro/core/MakeNewGeneration.kt
> +        val copy = copy(array)
Same as ce6c26af79f10e52e74e133e9169a5a862ff853c.
Please fix it as well.

2016-11-02 05:50 UTC, forestone23 commented on core/src/test/com.github.mmorihiro.core/TestMakeNewGeneration.kt
> +                val table = table(
Fixed in ce6c26af79f10e52e74e133e9169a5a862ff853c.

2016-11-02 05:51 UTC, forestone23 commented on core/src/test/com.github.mmorihiro.core/TestMakeNewGeneration.kt
> +            when there are three living cell adjacent to one dead cell""" {
Fixed in 78a8da16aa67698d564fe676432eeea151689e13.

2016-11-02 05:55 UTC, forestone23 commented on core/src/main/com/github/mmorihiro/core/MakeNewGeneration.kt
> +            for (j in array[0].indices) {
May I fix [MakeNewGeneration.kt#L28](https://github.com/mmorihiro/LifeGame/blob/78a8da16aa67698d564fe676432eeea151689e13/core/src/main/com/github/mmorihiro/core/MakeNewGeneration.kt#L28) and [MakeNewGeneration.kt#L42](https://github.com/mmorihiro/LifeGame/blob/78a8da16aa67698d564fe676432eeea151689e13/core/src/main/com/github/mmorihiro/core/MakeNewGeneration.kt#L42), too?

2016-11-02 05:58 UTC, forestone23 commented on core/src/main/com/github/mmorihiro/core/MakeNewGeneration.kt
> +        val copy = copy(array)
Fixed in 82e2ebd426297489439c61478e5c7c64249eaa0f.

2016-11-02 08:44 UTC, mmorihiro commented on core/src/main/com/github/mmorihiro/core/MakeNewGeneration.kt
> +            for (j in array[0].indices) {
Of course. I forgot to say that.

2016-11-02 08:46 UTC, forestone23 commented on core/src/main/com/github/mmorihiro/core/MakeNewGeneration.kt
> +            for (j in array[0].indices) {
Fixed in d6fa1d663184836952af6fbce0f2c24283c734c4.

2016-11-02 08:46 UTC, forestone23 approved these changes

2016-11-02 09:42 UTC, merged